name: photo_fixer
version: 1.0.0
publish_to: 'none'
description: Photo restoration app (scratch & blemish removal)
environment:
  sdk: ">=2.17.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  image_picker: ^1.0.0
  http: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  very_good_analysis: ^5.0.0
flutter:
  uses-material-design: true
